baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "https://o5m4n.github.io" # the base hostname & protocol for your site.

paginate: 6 #articles per pag
paginate_path: /page:num #makes pagination working


# header text
title: 05M4N
header: 
description: "Programming,Cybersecurity"
author:
  name: "05M4N"
  email: "egaro.148@gmail.com"

# for welcome page
# to replace image go to index.html
email:
  address: "edgaro.148@gmail.com"
  #text: "user (at) example.com"

# disqus comment
disqus:
    shortname: "test" #your disqus comment short name

# google analytics
google:
    tracking-id: "" #your tracking id here

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
  

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"

#permalink: /posts/:title

permalink: /:title

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  

# Custom variables
owner : "05m4n"
year : "2021"
